### PR TITLE
Review chapter 6 cadenas

### PR DESCRIPTION
**Pull request by danielmerino**
I have done a big revision of chapter 6, taking as source the very good translation of the previous Python 2 book to spanish.

-Fixed a lot of typos, specially of accents.
-Changed a few expressions from Latin America's spanish to a more worldwide spanish expressions (as they were in Python 2 book)
-I don't know Markdown, but in the translation the values inside index{} expressions have been translated, so I have edited them too. I.e: I have changed index{caracter} by index{carácter}

I will review the chapter again after the changes have been merged. I think that some expressions are messy and can be improved, but this is my personal point of view, so I prefer to submit them in a different PR for discussing.

### CODE REVIEW

**Comment by csev** [comment]
So just so you know, the translations for Chapter 6 and later are being handled differently than Chapters 1-5. Chapters 1-5 were translated by me / @csev a non-Spanish speaker pasting from the Python 2 Spanish book to the Python 3 book.  Chapters 6 and later are being translated by @don-charlie-pc - a native Spanish speaker. So I will give a chance to review these changes.

**Comment by csev** [comment]
Also @danielmerino - At some point please send a PR to include your name in the contribution appendix.  Once the book translation is complete - I will publish it on Amazon and add contributor names to the preface and first page material regarding the translation.  But I don't want to go too far without getting the appendix accurate.  Luckily github keeps track too :)

**Review by don-charlie-pc — COMMENTED** [review]
Thanks for fixing the typos and correcting some terminology @danielmerino ! It looks great to me.

**Comment by csev** [comment]
Yay!

**Pull request merged**
