### PR TITLE
Python scripts and reviews chapters 8-16

### PR DESCRIPTION
**Pull request by don-charlie-pc**
Adding the translation of all Python scripts used in chapters from 8 to 16. Update also the script output examples on the corresponding chapters.

### CODE REVIEW

**Comment by don-charlie-pc** [comment]
Hello @csev!
I am wondering, how do you generate the ZIP files used in chapter 16?
I would like to update the corresponding files as well as the output examples in chapter 16, but before editing the output examples, I need to be consistent with the scripts. Right now, if I download the scripts, they are on English, like for this file http://www.py4e.com/code3/pagerank.zip

**Comment by don-charlie-pc** [comment]
Oh, I just realized we may need to update the URLs to https://es.py4e.com/code3/
Plus, I just found the folders (corresponding to each zip file) inside the code3 folder. I will work on translating that!

**Comment by csev** [comment]
These look good enough to me.  I would merge them.   The next step is to make it so the unit tests actually work.  Once you settle master down for a bit, I will grab it and get the unit tests working for your translated code.  Let me know.

**Comment by csev** [comment]
There is a badly names cleanup.sh in the code3 folder that makes the zips.  But (unlike the HTML) I don't check them in - I just regenerate them in es.py4e.com

**Comment by don-charlie-pc** [comment]
I see! Thanks, I will let you know when we are ready for the unittests. It the server generates the zip files, then I just need to translate the content on the actual folders, without having to add the zip's. Anyway, I will add you as reviewer once I have those changes, so you can check I an not adding anything additional.

**Pull request merged**
