### PR TITLE
Chapters 08 and 09 - Translation to Spanish

### PR DESCRIPTION
**Pull request by don-charlie-pc**
Adding the translation to chapter 08 to Spanish.
Adding Juan Carlos name to the list of contributors.

### CODE REVIEW

**Comment by csev** [comment]
It looks great to me - and thanks for adding yourself to the contributors.  Since I don't know Spanish I will just merge this :)  Once you get to a nice milestone (i.e. Chapter 10) I can send a call out to the edX Spanish students to review the book and give us pull requests.   So it is better to get the base translation in and let folks review it from master.

**Comment by csev** [comment]
@don-charlie-pc I ran the scripts to update all the HTML copies of the books so don't be concerned when your next git pull has like 50 updated files.   They are all derived from the new chapters you and I have translated.

**Comment by csev** [comment]
I just fixed a Latex Syntax error in chapter 06 that was keeping the PDF from building completely.  You will see it in your next git pull and https://es.py4e.com/book in about 30 minutes.

**Comment by don-charlie-pc** [comment]
Thanks for fixing the error! I started working on the Chapter 10 translation, I'll be submitting the next pull request no later than the end of this week. It would be helpful to ask Spanish students to review the text, so they can identify any typo and help to fix it.

**Pull request merged**
